// <auto-generated />
using System;
using APDB_Kolokwium_template.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APDB_Kolokwium_template.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608141551_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Credits")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            ID = 101,
                            Credits = "3 ECTS",
                            Teacher = "dr Kowalski",
                            Title = "Wprowadzenie do Algorytmów"
                        },
                        new
                        {
                            ID = 102,
                            Credits = "4 ECTS",
                            Teacher = "mgr Nowicka",
                            Title = "Bazy Danych"
                        },
                        new
                        {
                            ID = 103,
                            Credits = "5 ECTS",
                            Teacher = "dr inż. Wiśniewski",
                            Title = "Programowanie Obiektowe"
                        });
                });

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Enrollment", b =>
                {
                    b.Property<int>("Student_ID")
                        .HasColumnType("int");

                    b.Property<int>("Course_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Student_ID", "Course_ID");

                    b.HasIndex("Course_ID");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            Student_ID = 1,
                            Course_ID = 101,
                            EnrollmentDate = new DateTime(2024, 10, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Student_ID = 2,
                            Course_ID = 102,
                            EnrollmentDate = new DateTime(2024, 10, 2, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Student_ID = 1,
                            Course_ID = 102,
                            EnrollmentDate = new DateTime(2024, 10, 3, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Student_ID = 3,
                            Course_ID = 103,
                            EnrollmentDate = new DateTime(2024, 10, 5, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "anna.nowak@example.edu",
                            FirstName = "Anna",
                            LastName = "Nowak"
                        },
                        new
                        {
                            ID = 2,
                            Email = "tomasz.w@example.edu",
                            FirstName = "Tomasz",
                            LastName = "Wiśniewski"
                        },
                        new
                        {
                            ID = 3,
                            Email = "katarzyna.kowalska@example.edu",
                            FirstName = "Katarzyna",
                            LastName = "Kowalska"
                        });
                });

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Enrollment", b =>
                {
                    b.HasOne("APDB_Kolokwium_template.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("Course_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APDB_Kolokwium_template.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("APDB_Kolokwium_template.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
